<?php

/**
* Implementation of hook_apachesolr_cck_fields_alter
*/
function solrcck_apachesolr_cck_fields_alter(&$mappings) {
  $mappings['number_integer'] = array(
    'optionwidgets_select' => array(
      'display_callback' => 'solrcck_basic_field_callback',
      'index_type' => 'integer',
    ),
    'number' => array(
      'display_callback' => 'solrcck_basic_field_callback',
      'index_type' => 'integer',
    ),
  );
}

/**
* A function that gets called during indexing.
* @node The current node being indexed
* @fieldname The current field being indexed
*
* @return an array of arrays. Each inner array is a value, and must be
* keyed 'value' => $value
*/
function solrcck_basic_field_callback($node, $fieldname) {
  $fields = array();
  foreach ($node->$fieldname as $field) {
    $fields[] = array('value' => $field['value']);
  }
  return $fields;
}
